// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj-HyGDFAm-wOXu5_rAWelGfRfenn-xtc',
    appId: '1:610827342587:web:2d2868e961029fc4af965e',
    messagingSenderId: '610827342587',
    projectId: 'babble-815fb',
    authDomain: 'babble-815fb.firebaseapp.com',
    storageBucket: 'babble-815fb.appspot.com',
    measurementId: 'G-W13WL0PZGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmRjHAOuWA8d4usu1TF1unsRyCdxrf160',
    appId: '1:610827342587:android:cac9c53fd578c2a0af965e',
    messagingSenderId: '610827342587',
    projectId: 'babble-815fb',
    storageBucket: 'babble-815fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ590oEgk89wlFTa97gPIZ8z6LOJtQYJQ',
    appId: '1:610827342587:ios:004648a8368288acaf965e',
    messagingSenderId: '610827342587',
    projectId: 'babble-815fb',
    storageBucket: 'babble-815fb.appspot.com',
    iosClientId: '610827342587-jir5st9k8s8b7dbu6tit07817cjff59e.apps.googleusercontent.com',
    iosBundleId: 'com.sukhwinder.singh.babble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ590oEgk89wlFTa97gPIZ8z6LOJtQYJQ',
    appId: '1:610827342587:ios:004648a8368288acaf965e',
    messagingSenderId: '610827342587',
    projectId: 'babble-815fb',
    storageBucket: 'babble-815fb.appspot.com',
    iosClientId: '610827342587-jir5st9k8s8b7dbu6tit07817cjff59e.apps.googleusercontent.com',
    iosBundleId: 'com.sukhwinder.singh.babble',
  );
}
